import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerate with: npm run gen-api-docs pathmgmt
import apiSidebar from './docs/api-reference/rest/sidebar';

/**
 * Top-level categories mirror the shape shared across warehouse-systems
 * documentation sites: Overview, Operations, Development, Domain-Driven
 * Design, API Reference, Ecosystem, Architecture Decision Records.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {type: 'doc', id: 'overview/introduction'},
      items: [
        'overview/introduction',
        'overview/architecture',
        'overview/quickstart',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/configuration',
        'operations/runbook',
        'operations/observability',
        'operations/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: ['development/testing'],
    },
    'ddd/ubiquitous-language',
    'ddd/aggregates-and-invariants',
    {
      type: 'category',
      label: 'DDD artifacts (ddd-crew)',
      link: {type: 'doc', id: 'ddd/ddd-artifacts'},
      items: [
        'ddd/core-domain-chart',
        'ddd/bounded-context-canvas',
        'ecosystem/context-map',
        'ddd/aggregate-design-canvas',
        'ddd/domain-message-flow',
        'ddd/eventstorming',
        'ddd/class-diagram',
        'ddd/entity-relationship',
        'ddd/sequence-diagrams',
        'ddd/domain-events',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api-reference/rest/process-path-management-api'},
      items: [...apiSidebar],
    },
    'mcp/governance-charter',
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {type: 'doc', id: 'adr/about'},
      items: [
        'adr/0001-process-path-management-bounded-context',
        'adr/0002-yaml-to-kafka-cutover',
        'adr/0003-transactional-outbox',
        'adr/0004-rest-auth-adoption',
        'adr/0005-remove-rest-auth',
        'adr/0006-mcp-server-second-inbound-adapter',
        'adr/0007-analytical-data-product',
        'adr/0008-fclm-aligned-process-path-families',
        'adr/0009-destination-location-role-on-process-path',
        'adr/0010-fulfillment-capability-contract',
        'adr/0011-idempotency-key-middleware',
        'adr/0012-kafka-dlq-and-graceful-shutdown',
        'adr/0013-kafka-writer-hash-balancer',
        'adr/0014-horizontal-autoscaling-and-pgxpool-tuning',
        'adr/0015-migrations-direct-postgres-connection',
        'adr/0016-cloudevents-mandatory-event-envelope',
        'adr/0017-optimistic-concurrency-version-column',
        'adr/0018-outbox-lag-gauge-and-housekeeping-sweeper',
        'adr/0019-standard-metrics-convention',
        'adr/0020-rfc-7807-problem-details',
        'adr/0021-architecture-fitness-suite',
        'adr/0022-mfe-console-remote',
        'adr/0023-mcp-eval-and-governance-harness',
        'adr/0024-bootretry-for-istio-native-sidecar-warmup',
        'adr/0025-schemathesis-contract-job',
        'adr/0026-reject-deactivation-of-paths-in-cpt-schedules',
        'adr/0027-w3c-trace-context-on-kafka-headers',
        'adr/0028-close-path-cpt-schedule-race-with-row-locks',
      ],
    },
  ],
};

export default sidebars;
